spring.application.name=musteri-faturalama-sistemi

spring.datasource.url=jdbc:postgresql://postgres-docker:5432/faturalamadb
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=bu-cok-gizli-bir-anahtar-en-az-32-karakter-olmali-guvenlik-icin-uzun-tutuyoruz
jwt.expiration=86400000